---
- name: WG-Container present
  docker_container:
    name: wg-docker
    image: klausdieter371/wg-docker:latest
    privileged: true
    network_mode: host
    capabilities:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    sysctls:
      net.ipv6.conf.all.forwarding: '1'
      net.ipv6.conf.all.accept_redirects: '0'
      net.ipv4.conf.all.rp_filter: '0'
    restart: yes

- name: yanic-Container present
  docker_container:
    name: yanic
    image: ffmd/yanic:latest
    network_mode: host
    restart: yes

- name: dns64-Container present
  docker_container:
    name: dns64
    image: ffmd/dns64:latest
    command: named
    ports:
      - 127.0.0.1:53:53/tcp
      - 127.0.0.1:53:53/udp
    restart: yes

- name: jool-Container present
  docker_container:
    name: jool
    image: ffmd/jool:latest
    command: '/root/run.sh'
    network_mode: host
    privileged: true
    capabilities:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    sysctls:
      net.ipv6.conf.all.forwarding: '1'
      net.ipv6.conf.all.accept_redirects: '0'
      net.ipv4.conf.all.rp_filter: '0'
    restart: yes
