---
# FIXME: We should use tags or commit hashes here
- src: https://github.com/geerlingguy/ansible-role-ntp
  name: ntp
- src: https://github.com/weareinteractive/ansible-ufw
  name: ufw
- src: https://github.com/weareinteractive/ansible-sudo
  name: sudo
- src: https://github.com/robertdebock/ansible-role-openssh
  name: sshd
