---
- name: install required packages
  package:
    state: present
    name:
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      - python3-pip

- name: Add an Apt signing key for docker repo
  apt_key:
    state: present
    id: 0EBFCD88
    url: https://download.docker.com/linux/debian/gpg

- name: Add Docker-CE Upstream Repository
  apt_repository:
    state: present
    repo: deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_lsb.codename|lower }} stable
    update_cache: yes

- name: Install Docker-CE
  package:
    state: present
    name:
      -  docker-ce

- name: Start Docker Service
  service:
    state: started
    enabled: true
    name: docker
